jasypt:
    encryptor:
        password: lemur
my:
    secret: ${random.value}
    name: ${my.secret} sss
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;
            filters: stat
            initialSize: 1
            maxActive: 20
            maxOpenPreparedStatements: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            poolPreparedStatements: true
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            validationQuery: SELECT 'x'
        password: ENC(6x0x0le3L6fzKoZySVofFsKXVNem5PXayWQ7WTjpKgfuRfUeeMXVHXlrdsMvKWqu)
        url: jdbc:mysql://127.0.0.1:3306/bjpowernode?serverTimezone=GMT-8
        username: ENC(5YqbOPi6rhrc95cfdNUfrMm2UCEx7t99ivaIXIiGPjTdf7wRL01AY9V4WXVolTJB)
    mvc:
        view:
            prefix: /
            suffix: .jsp
